"""
Predictive alert models for Project AEGIS.

This module contains data structures for failure predictions.
"""

import uuid
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from src.models.enums import AlertSeverity, FailureCategory


class PredictiveAlert(BaseModel):
    """Alert generated by ML model or rule-based engine."""

    alert_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()), description="Unique alert identifier"
    )
    vehicle_id: str
    timestamp: datetime
    severity: AlertSeverity
    category: FailureCategory

    component: str = Field(..., description="Specific component (e.g., 'engine_temp')")
    failure_probability: float = Field(
        ..., ge=0, le=1, description="Probability of failure (0.0-1.0)"
    )
    confidence: float = Field(..., ge=0, le=1, description="Model confidence score (0.0-1.0)")

    # Prediction Time Window
    predicted_failure_min_hours: float = Field(..., ge=0, description="Minimum hours until failure")
    predicted_failure_max_hours: float = Field(..., ge=0, description="Maximum hours until failure")
    predicted_failure_likely_hours: float = Field(
        ..., ge=0, description="Most likely hours until failure"
    )

    # Actionable Information
    can_complete_current_mission: bool = Field(..., description="Safe to complete current mission")
    recommended_action: str = Field(..., description="Human-readable recommended action")
    safe_to_operate: bool = Field(..., description="Vehicle safe for operation")

    # Context & Metadata
    contributing_factors: list[str] = Field(
        default_factory=list, description="List of contributing telemetry anomalies"
    )
    related_telemetry: dict[str, Any] = Field(
        default_factory=dict, description="Snapshot of relevant telemetry values"
    )
    model_version: str = Field(default="1.0.0", description="ML model version that generated alert")

    # Orchestrator Response
    acknowledged: bool = Field(default=False, description="Alert acknowledged by orchestrator")
    acknowledged_by: str | None = None
    acknowledged_at: datetime | None = None

    model_config = {
        "json_schema_extra": {
            "example": {
                "alert_id": "alert-550e8400-e29b-41d4-a716-446655440000",
                "vehicle_id": "AMB-001",
                "timestamp": "2026-02-10T14:32:15.000Z",
                "severity": "warning",
                "category": "electrical",
                "component": "alternator",
                "failure_probability": 0.75,
                "confidence": 0.88,
                "predicted_failure_min_hours": 8.0,
                "predicted_failure_max_hours": 24.0,
                "predicted_failure_likely_hours": 12.0,
                "can_complete_current_mission": True,
                "safe_to_operate": True,
                "recommended_action": "Schedule alternator inspection within 12 hours",
                "contributing_factors": [
                    "battery_voltage declining trend",
                    "alternator_voltage below 13.5V",
                    "increased electrical load",
                ],
                "model_version": "1.0.0",
            }
        }
    }


class CrimePrediction(BaseModel):
    """City-level ML risk prediction generated by the orchestrator."""

    prediction_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique prediction identifier",
    )
    neighborhood: str = Field(..., min_length=1)
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Prediction creation timestamp",
    )
    risk_probability: float = Field(..., ge=0, le=1)
    confidence: float = Field(..., ge=0, le=1)
    severity: AlertSeverity
    latitude: float = Field(..., ge=-90, le=90)
    longitude: float = Field(..., ge=-180, le=180)
    predicted_crime_type: str = Field(..., min_length=1)
    description: str = Field(..., min_length=1)
    source: str = Field(default="ai_crime_predictor")
